apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: opslora-test-ns
  labels:
    app: auth
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels: 
      app: auth-microservice
  template:
    metadata:
      labels:
        app: auth-microservice
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: auth-app
                topologyKey: kubernetes.io/hostname
      containers:
        - name: auth-container
          image: kubectlandchill/sales-auth-service:v1.2.2
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "200m"
              memory: "300Mi"
              ephemeral-storage: "500Mi"
            requests:
              cpu: "100m"
              memory: "150Mi"
              ephemeral-storage: "250Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/auth/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3